name: terminev
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_pty: ^0.3.0
  bitsdojo_window: ^0.1.2
  xterm:
    git:
      url: https://github.com/dahliaOS/xterm.git
  hooks_riverpod: ^1.0.4
  flutter_hooks: ^0.18.5+1
  gap: ^2.0.0
  path_provider: ^2.0.11
  yaml: ^3.1.1
  titlebar_buttons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
